- src/main/java/es/princip/getp/domain/people/domain/entity/People.java
- src/main/java/es/princip/getp/domain/people/dto/request/CreatePeopleRequest.java
- src/main/java/es/princip/getp/domain/people/dto/request/UpdatePeopleRequest.java
- src/main/java/es/princip/getp/domain/people/dto/response/people/CreatePeopleResponse.java
- src/main/java/es/princip/getp/domain/people/dto/response/people/PeopleResponse.java
- src/main/java/es/princip/getp/domain/people/dto/response/people/UpdatePeopleResponse.java
- src/test/java/es/princip/getp/domain/client/controller/ClientControllerTest.java
- src/test/java/es/princip/getp/domain/client/controller/MyClientControllerTest.java
- src/test/java/es/princip/getp/domain/people/repository/PeopleRepositoryTest.java
- src/test/java/es/princip/getp/domain/people/service/PeopleServiceTest.java
- src/test/java/es/princip/getp/fixture/PeopleFixture.java
- 요구사항 변경에 따른 피플 정보 계좌 필드 삭제
- X
- 테스트 코드 수정 중, 사용하고 있지 않는 로거 `@Slf4j`를 삭제하였습니다!
> GETP-75 chore: 요구사항 변경에 따른 피플 정보 수정

- dev.sh
- test.sh
- Github Action 워크 플로우 실행 중 예외가 발생할 경우 워크 플로우가 실패하도록 쉘 스크립트 수정
- 
-
>  feat: Github Action 실패 감지 기능 추가

- .github/workflows/deploy-develop-branch.yml
- .github/workflows/pull-request-merge.yml
- src/test/resources/application-test.yml
- Github Action JUnit 테스트 결과 보고서 기능 추가
- 
-
> chore: Github Action JUnit 테스트 결과 보고서 기능 추가

- build.gradle
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/people/get-people.adoc
- src/main/java/es/princip/getp/domain/people/controller/PeopleController.java
- src/main/java/es/princip/getp/domain/people/domain/entity/People.java
- src/main/java/es/princip/getp/domain/people/dto/response/people/DetailPeopleResponse.java
- src/main/java/es/princip/getp/domain/people/dto/response/people/PublicDetailPeopleResponse.java
- src/main/java/es/princip/getp/domain/people/dto/response/peopleProfile/DetailPeopleProfileResponse.java
- src/main/java/es/princip/getp/domain/people/dto/response/peopleProfile/PublicDetailPeopleProfileResponse.java
- src/main/java/es/princip/getp/domain/people/repository/PeopleQueryDslRepositoryImpl.java
- src/main/java/es/princip/getp/global/support/ControllerSupport.java
- src/test/java/es/princip/getp/domain/people/controller/PeopleControllerTest.java
- src/test/java/es/princip/getp/domain/people/fixture/PeopleProfileFixture.java
- src/test/java/es/princip/getp/global/support/AbstractControllerTest.java
- 피플 상세 정보 조회 기능 컨트롤러 단위 테스트 작성
- 다음 PR에서 피플과 의뢰자의 공통 필드를 회원으로 리팩토링 진행할 예정입니다.
-
> test: 피플 상세 정보 조회 기능 컨트롤러 단위 테스트 작성

- src/docs/asciidoc/auth/send-email-verification-code-for-sign-up.adoc
- src/docs/asciidoc/index.adoc
- src/test/java/es/princip/getp/domain/auth/controller/SignUpControllerTest.java
- src/test/java/es/princip/getp/domain/auth/support/SignUpFixture.java
- 회원 가입 시 이메일 인증 코드 전송 컨트롤러 단위 테스트 및 API 문서 작성
- 
-
> GETP-145 test: 회원 가입 시 이메일 인증 코드 전송 컨트롤러 단위 테스트 및 API 문서 작성

- .github/workflows/deploy-develop-branch.yml
- Github Action Self-Hosted Runner 테스트용 PR입니다.
- 
-
> test: Github Action Self-Hosted Runner 테스트

- src/main/java/es/princip/getp/domain/auth/presentation/AuthController.java
- src/main/java/es/princip/getp/domain/auth/presentation/SignUpController.java
- src/main/java/es/princip/getp/domain/client/command/presentation/MyClientController.java
- src/main/java/es/princip/getp/domain/client/query/presentation/ClientQueryController.java
- src/main/java/es/princip/getp/domain/client/query/presentation/MyClientQueryController.java
- src/main/java/es/princip/getp/domain/member/command/presentation/MyMemberController.java
- src/main/java/es/princip/getp/domain/people/command/presentation/MyPeopleController.java
- src/main/java/es/princip/getp/domain/people/command/presentation/MyPeopleProfileController.java
- src/main/java/es/princip/getp/domain/people/command/presentation/PeopleLikeController.java
- src/main/java/es/princip/getp/domain/people/query/presentation/MyPeopleProfileQueryController.java
- src/main/java/es/princip/getp/domain/people/query/presentation/MyPeopleQueryController.java
- src/main/java/es/princip/getp/domain/people/query/presentation/PeopleQueryController.java
- src/main/java/es/princip/getp/domain/project/command/presentation/ProjectApplicationController.java
- src/main/java/es/princip/getp/domain/project/command/presentation/ProjectController.java
- src/main/java/es/princip/getp/domain/project/command/presentation/ProjectLikeController.java
- src/main/java/es/princip/getp/domain/project/query/presentation/ProjectQueryController.java
- src/main/java/es/princip/getp/infra/dto/response/ApiResponse.java
- src/main/java/es/princip/getp/infra/exception/DefaultErrorCode.java
- src/main/java/es/princip/getp/infra/exception/ErrorDescription.java
- src/main/java/es/princip/getp/infra/exception/handler/AccessDeniedExceptionHandler.java
- src/main/java/es/princip/getp/infra/exception/handler/BusinessLogicExceptionHandler.java
- src/main/java/es/princip/getp/infra/exception/handler/DefaultExceptionHandler.java
- src/main/java/es/princip/getp/infra/exception/handler/EntityNotFoundExceptionHandler.java
- src/main/java/es/princip/getp/infra/exception/handler/MethodArgumentNotValidExceptionHandler.java
- src/main/java/es/princip/getp/infra/security/exception/handler/BadCredentialsHandler.java
- 해당 엔티티가 존재하지 않는 예외를 처리하기 위한 EntityNotFoundExceptionHandler 구현
- 
-
> feat: 해당 엔티티가 존재하지 않는 예외를 처리하기 위한 EntityNotFoundExceptionHandler 구현

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/project/like-project.adoc
- src/docs/asciidoc/project/unlike-project.adoc
- src/main/java/es/princip/getp/domain/people/command/domain/People.java
- src/main/java/es/princip/getp/domain/people/exception/ProjectNeverLikedException.java
- src/main/java/es/princip/getp/domain/project/command/application/ProjectLikeService.java
- src/main/java/es/princip/getp/domain/project/command/presentation/ProjectLikeController.java
- src/test/java/es/princip/getp/domain/people/command/domain/PeopleTest.java
- src/test/java/es/princip/getp/domain/project/command/presentation/ProjectLikeControllerTest.java
- src/test/java/es/princip/getp/infra/support/AbstractControllerTest.java
> feat: 프로젝트 좋아요 취소 기능 구현

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/project/get-project-by-project-Id.adoc
- src/main/java/es/princip/getp/domain/project/query/presentation/ProjectQueryController.java
- src/test/java/es/princip/getp/domain/project/query/presentation/ProjectQueryControllerTest.java
- src/test/java/es/princip/getp/domain/project/query/presentation/description/ProjectDetailResponseDescription.java
- 프로젝트 상세 조회 컨트롤러 단위 테스트 작성
- 
-
> GETP-154 test: 프로젝트 상세 조회 컨트롤러 단위 테스트 작성

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/project/get-projects.adoc
- src/main/java/es/princip/getp/domain/project/query/presentation/ProjectQueryController.java
- src/test/java/es/princip/getp/domain/member/fixture/NicknameFixture.java
- src/test/java/es/princip/getp/domain/project/query/presentation/ProjectQueryControllerTest.java
- 프로젝트 목록 조회 컨트롤러 단위 테스트 작성
- 
-
> test: 프로젝트 목록 조회 컨트롤러 단위 테스트 작성

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/my-client/get-my-client.adoc
- src/test/java/es/princip/getp/domain/client/query/presentation/MyClientQueryControllerTest.java
- src/test/java/es/princip/getp/domain/client/query/presentation/description/ClientResponseDescription.java
- 내 의뢰자 정보 조회 컨트롤러 단위 테스트 작성
- 
-
> GETP-163 test: 내 의뢰자 정보 조회 컨트롤러 단위 테스트 작성

- src/main/java/es/princip/getp/domain/common/annotation/URLPattern.java
- src/main/java/es/princip/getp/domain/common/domain/URL.java
- src/main/java/es/princip/getp/domain/people/command/presentation/dto/request/PortfolioRequest.java
- `@URLValid`에서 `@URLPattern`으로 변경
- 
-
> rename: `@URLValid`에서 `@URLPattern`으로 변경

- src/main/java/es/princip/getp/domain/common/annotation/Enum.java
- src/main/java/es/princip/getp/domain/people/command/presentation/dto/request/CreatePeopleRequest.java
- src/main/java/es/princip/getp/domain/people/command/presentation/dto/request/UpdatePeopleRequest.java
- src/main/java/es/princip/getp/domain/project/command/presentation/dto/request/CommissionProjectRequest.java
-  `@Enum`을 infra.annotation에서 domain.common.annotation으로 이동
- 
-
> rename: `@Enum`을 infra.annotation에서 domain.common.annotation으로 이동

- src/main/java/es/princip/getp/domain/project/command/application/ProjectCommissionService.java
- src/main/java/es/princip/getp/domain/project/command/application/ProjectDataMapper.java
- src/main/java/es/princip/getp/domain/project/command/application/command/CommissionProjectCommand.java
- src/main/java/es/princip/getp/domain/project/command/domain/ProjectCommissioner.java
- src/main/java/es/princip/getp/domain/project/command/presentation/ProjectCommandMapper.java
- src/main/java/es/princip/getp/domain/project/command/presentation/ProjectCommissionController.java
- src/main/java/es/princip/getp/domain/project/command/presentation/dto/response/CommissionProjectResponse.java
- src/test/java/es/princip/getp/domain/project/command/domain/ProjectCommissionerTest.java
- src/test/java/es/princip/getp/domain/project/command/presentation/ProjectCommissionControllerTest.java
- registerProject에서 commissionProject로 변경
- 
-
> rename: registerProject에서 commissionProject로 변경

- src/main/java/es/princip/getp/domain/client/query/dto/ClientResponse.java
- src/main/java/es/princip/getp/domain/common/domain/Hashtag.java
- src/main/java/es/princip/getp/domain/common/domain/TechStack.java
- src/main/java/es/princip/getp/domain/people/command/application/PeopleProfileService.java
- src/main/java/es/princip/getp/domain/project/query/dao/MyProjectQueryDslDao.java
- src/main/java/es/princip/getp/domain/project/query/dao/ProjectQueryDslDao.java
- src/main/java/es/princip/getp/domain/project/query/dto/MyProjectCardResponse.java
- src/main/java/es/princip/getp/domain/project/query/dto/ProjectCardResponse.java
- src/test/java/es/princip/getp/domain/common/fixture/HashtagFixture.java
- src/test/java/es/princip/getp/domain/common/fixture/TechStackFixture.java
- src/test/java/es/princip/getp/domain/project/fixture/ProjectFixture.java
- src/test/java/es/princip/getp/domain/project/query/presentation/ProjectQueryControllerTest.java
- 정적 팩토리 메소드의 이름을 인자 개수가 하나면 `from`, 둘 이상이면 `of`로 수정
- 
-
> style: 정적 팩토리 메소드의 이름을 인자 개수가 하나면 `from`, 둘 이상이면 `of`로 수정

- src/main/java/es/princip/getp/domain/people/query/dao/PeopleQueryDslDao.java
- src/main/java/es/princip/getp/domain/people/query/dto/people/CardPeopleResponse.java
- src/main/java/es/princip/getp/domain/people/query/dto/people/DetailPeopleResponse.java
- src/main/java/es/princip/getp/domain/people/query/dto/people/PeopleResponse.java
- src/main/java/es/princip/getp/domain/people/query/dto/people/PublicDetailPeopleResponse.java
- src/main/java/es/princip/getp/domain/people/query/dto/peopleProfile/CardPeopleProfileResponse.java
- src/test/java/es/princip/getp/domain/people/query/infra/PeopleDaoConfig.java
- src/test/java/es/princip/getp/domain/people/query/presentation/PeopleQueryControllerTest.java
- src/test/java/es/princip/getp/domain/people/query/presentation/description/response/DetailPeopleResponseDescription.java
- src/test/java/es/princip/getp/domain/people/query/presentation/description/response/PeopleResponseDescription.java
- src/test/java/es/princip/getp/domain/people/query/presentation/description/response/PublicDetailPeopleResponseDescription.java
> GETP-171 feat: 피플 목록 조회 DTO에 소개 필드 추가

- src/main/java/es/princip/getp/domain/member/command/application/MemberService.java
- src/main/java/es/princip/getp/domain/member/command/exception/AlreadyUsedEmailException.java
- src/main/java/es/princip/getp/domain/member/command/exception/FailedToSaveProfileImageException.java
- src/main/java/es/princip/getp/domain/member/command/exception/NotFoundMemberException.java
- src/main/java/es/princip/getp/domain/member/command/infra/ServiceTermAgreementServiceImpl.java
- src/main/java/es/princip/getp/domain/serviceTerm/application/ServiceTermService.java
- src/main/java/es/princip/getp/domain/serviceTerm/exception/DuplicatedTagException.java
- src/main/java/es/princip/getp/domain/serviceTerm/exception/NotAgreedAllRequiredServiceTermException.java
- src/main/java/es/princip/getp/domain/serviceTerm/exception/NotFoundServiceTermException.java
- src/main/java/es/princip/getp/domain/serviceTerm/infra/ServiceTermCheckerImpl.java
- 회원 도메인의 사용자에게 반환할 에러 메시지에 대한 책임을 사용자 정의 예외로 이동
- 
-
> refactor: 회원 도메인의 사용자에게 반환할 에러 메시지에 대한 책임을 사용자 정의 예외로 이동

- src/main/java/es/princip/getp/domain/people/query/dao/PeopleDao.java
- src/main/java/es/princip/getp/domain/people/query/dao/PeopleQueryDslDao.java
- src/main/java/es/princip/getp/domain/people/query/dto/people/MyPeopleResponse.java
- src/main/java/es/princip/getp/domain/people/query/presentation/MyPeopleQueryController.java
- src/test/java/es/princip/getp/domain/people/query/dao/PeopleDaoTest.java
- src/test/java/es/princip/getp/domain/people/query/presentation/MyPeopleQueryControllerTest.java
- src/test/java/es/princip/getp/domain/people/query/presentation/description/response/MyPeopleResponseDescription.java
- 내 피플 정보 조회 DTO에 전화번호 필드 추가
- 
-
> GETP-172 feat: 내 피플 정보 조회 DTO에 전화번호 필드 추가

- .github/workflows/deploy-develop-branch.yml
- Github Action 배포 워크 플로우 클릭을 통해 실행할 수 있도록 `workflow_dispatch` 이벤트 추가
- 
-
> feat: Github Action 배포 워크 플로우 클릭을 통해 실행할 수 있도록 `workflow_dispatch` 이벤트 추가

- src/docs/asciidoc/index.adoc
> GETP-170 docs: 파일 업로드 API 문서 작성

- src/main/java/es/princip/getp/domain/member/command/domain/service/ProfileImageService.java
- src/main/java/es/princip/getp/infra/storage/infra/LocalImageStorage.java
- src/main/java/es/princip/getp/infra/util/ImageUtil.java
- 사진 업로드 시 Tika를 이용한 검증에서 Content-Type을 비교한 검증으로 변경해 사진이 깨지는 오류 수정
- 스토리지에 대한 아키텍쳐 및 URL 설계에 대해 고민해봐야 할 것 같습니다. 일단 구현 먼저 해놓은 방향으로..
-
> fix: 사진 업로드 시 Tika를 이용한 검증에서 Content-Type을 비교한 검증으로 변경해 사진이 깨지는 오류 수정

- src/docs/asciidoc/index.adoc
- src/main/java/es/princip/getp/domain/project/query/dao/MyCommissionedProjectDao.java
- src/main/java/es/princip/getp/domain/project/query/dao/MyCommissionedProjectQueryDslDao.java
- src/main/java/es/princip/getp/domain/project/query/dao/ProjectDaoUtil.java
- src/main/java/es/princip/getp/domain/project/query/dao/ProjectQueryDslDao.java
- src/main/java/es/princip/getp/domain/project/query/dto/MyCommissionedProjectCardResponse.java
- src/main/java/es/princip/getp/domain/project/query/presentation/MyCommissionedProjectQueryController.java
- src/test/java/es/princip/getp/domain/project/fixture/ProjectApplicationFixture.java
- src/test/java/es/princip/getp/domain/project/query/dao/MyCommissionedProjectDaoTest.java
- src/test/java/es/princip/getp/domain/project/query/infra/MyProjectDaoConfig.java
- src/test/java/es/princip/getp/domain/project/query/presentation/MyCommissionedProjectQueryControllerTest.java
- src/test/java/es/princip/getp/domain/project/query/presentation/description/GetMyCommissionedProjectQueryParameterDescription.java
- 의뢰한 프로젝트 목록 조회 API 엔드 포인트를 `/client/me/projects`로 변경
- 
-
> GETP-186 feat: 의뢰한 프로젝트 목록 조회 API 엔드 포인트를 `/client/me/projects`로 변경

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/project/apply-for-project.adoc
- src/main/java/es/princip/getp/domain/project/command/application/ProjectApplicationService.java
- src/main/java/es/princip/getp/domain/project/command/domain/ProjectApplier.java
- src/main/java/es/princip/getp/domain/project/exception/AlreadyAppliedProjectException.java
- src/test/java/es/princip/getp/domain/project/command/presentation/ProjectApplicationControllerTest.java
- src/test/java/es/princip/getp/domain/project/command/presentation/description/ApplyProjectRequestDescription.java
- src/test/java/es/princip/getp/domain/project/command/presentation/description/ApplyProjectResponseDescription.java
- 같은 프로젝트에 중복으로 지원이 가능한 오류 수정
- 
-
> GETP-188 fix: 같은 프로젝트에 중복으로 지원이 가능한 오류 수정

- src/main/java/es/princip/getp/domain/auth/application/port/out/SaveEmailVerificationPort.java
- src/main/java/es/princip/getp/domain/auth/application/port/out/SaveRefreshTokenPort.java
- src/main/java/es/princip/getp/domain/client/command/application/port/out/DeleteClientPort.java
- src/main/java/es/princip/getp/domain/client/command/application/port/out/LoadClientPort.java
- src/main/java/es/princip/getp/domain/client/command/application/port/out/SaveClientPort.java
- src/main/java/es/princip/getp/domain/client/command/application/port/out/UpdateClientPort.java
- src/main/java/es/princip/getp/domain/like/command/port/out/LoadLikePort.java
- src/main/java/es/princip/getp/domain/like/command/port/out/SaveLikePort.java
- src/main/java/es/princip/getp/domain/like/command/port/out/SaveUnlikePort.java
- src/main/java/es/princip/getp/domain/people/command/domain/PeopleId.java
- src/main/java/es/princip/getp/domain/people/command/port/out/CheckPeoplePort.java
- src/main/java/es/princip/getp/domain/people/command/port/out/LoadPeoplePort.java
- src/main/java/es/princip/getp/domain/people/command/port/out/SavePeoplePort.java
- src/main/java/es/princip/getp/domain/people/command/port/out/UpdatePeoplePort.java
- src/main/java/es/princip/getp/domain/project/port/out/CheckProjectApplicationPort.java
- src/main/java/es/princip/getp/domain/project/port/out/CheckProjectMeetingPort.java
- src/main/java/es/princip/getp/domain/project/port/out/CheckProjectPort.java
- src/main/java/es/princip/getp/domain/project/port/out/LoadProjectApplicationPort.java
- src/main/java/es/princip/getp/domain/project/port/out/LoadProjectMeetingPort.java
- src/main/java/es/princip/getp/domain/project/port/out/LoadProjectPort.java
- src/main/java/es/princip/getp/domain/project/port/out/SaveProjectApplicationPort.java
- src/main/java/es/princip/getp/domain/project/port/out/SaveProjectMeetingPort.java
- src/main/java/es/princip/getp/domain/project/port/out/SaveProjectPort.java
- src/main/java/es/princip/getp/domain/project/port/out/UpdateProjectApplicationPort.java
- src/main/java/es/princip/getp/domain/project/port/out/UpdateProjectMeetingPort.java
- src/main/java/es/princip/getp/domain/project/port/out/UpdateProjectPort.java
- src/main/java/es/princip/getp/domain/serviceTerm/port/out/CheckServiceTermPort.java
- src/main/java/es/princip/getp/domain/serviceTerm/port/out/LoadServiceTermPort.java
- src/main/java/es/princip/getp/domain/serviceTerm/port/out/SaveServiceTermPort.java
- src/main/java/es/princip/getp/domain/serviceTerm/port/out/UpdateServiceTermPort.java
- `Application Out Port `인터페이스 생성
- X
- 포트-어댑터 아키텍처를 적용할 때, 각자의 작업 도메인을 `OutPort` 인터페이스로  분담하여 협업을 원활하게 함
> GETP-195 refactor: Application Out Port 인터페이스 생성

- .github/ISSUE_TEMPLATE/-bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
Github Feature Request, Bug Report 이슈 템플릿 추가
> DOCS: Issue Template 추가

- build.gradle
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/db/migration/V1__init.sql
- 데이터베이스 마이그레이션을 위한 Flyway 도입
- 
-
> GETP-225 chore: 데이터베이스 마이그레이션을 위한 Flyway 도입

- src/main/java/es/princip/getp/api/controller/project/query/dto/ProjectDetailResponse.java
- src/main/java/es/princip/getp/application/project/apply/port/out/CountProjectApplicationPort.java
- src/main/java/es/princip/getp/persistence/adapter/project/apply/CountProjectApplicationAdapter.java
- src/main/java/es/princip/getp/persistence/adapter/project/commission/FindProjectAdapter.java
- src/test/java/es/princip/getp/api/controller/project/query/ProjectQueryControllerTest.java
- src/test/java/es/princip/getp/api/controller/project/query/description/ProjectDetailResponseDescription.java
- src/test/java/es/princip/getp/persistence/adapter/project/apply/CountProjectApplicationAdapterTest.java
- 프로젝트 상세 조회 DTO에 지원자 수 필드 추가
- 
-
> GETP-242 feat: 프로젝트 상세 조회 DTO에 지원자 수 필드 추가

- src/main/java/es/princip/getp/persistence/adapter/project/commission/FindProjectAdapter.java
- 프로젝트 목록 조회의 필터링 적용 시 회원 ID를 비교하지 않던 오류 수정
- 
-
> GETP-120 fix: 프로젝트 목록 조회의 필터링 적용 시 회원 ID를 비교하지 않던 오류 수정

- src/main/java/es/princip/getp/api/security/SecurityConfig.java
- CORS 허용 출처에 api.principes.xyz 추가
- 
-
> chore: CORS 허용 출처에 api.principes.xyz 추가

- src/main/java/es/princip/getp/api/controller/people/query/PeopleQueryController.java
- src/main/java/es/princip/getp/persistence/adapter/like/people/PeopleLikePersistenceAdapter.java
- src/main/java/es/princip/getp/persistence/adapter/like/project/ProjectLikePersistenceAdapter.java
- 피플 좋아요 여부 메소드에 member 객체 null 체크 추가
- 
-
> GETP-308 fix: 피플 좋아요 여부 메소드에 member 객체 null 체크 추가

- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/project/get-application-form.adoc
- src/main/java/es/princip/getp/api/controller/project/query/ProjectApplicationFormQueryController.java
- src/main/java/es/princip/getp/api/controller/project/query/dto/ProjectApplicationDetailTeammateResponse.java
- src/main/java/es/princip/getp/api/controller/project/query/dto/ProjectApplicationFormResponse.java
- src/main/java/es/princip/getp/application/project/apply/GetApplicationDetailService.java
- src/main/java/es/princip/getp/application/project/apply/GetApplicationFormService.java
- src/main/java/es/princip/getp/application/project/apply/ProjectApplicationDetailResponseFactory.java
- src/main/java/es/princip/getp/application/project/apply/ProjectApplicationDetailTeammateResponseFactory.java
- src/main/java/es/princip/getp/application/project/apply/ProjectApplicationFormResponseFactory.java
- src/main/java/es/princip/getp/application/project/apply/port/in/GetApplicationFormQuery.java
- src/test/java/es/princip/getp/api/controller/project/query/ProjectApplicationDetailFormControllerTest.java
- src/test/java/es/princip/getp/api/controller/project/query/description/ProjectApplicationFormResponseDescription.java
> GETP-217 feat: 프로젝트 지원서 조회 API 구현

- .github/workflows/deploy-test-toothless.yml
> chore: 테스트 서버 배포 스크립트 작성
