Principes-Artis-Mechanicae/get-p-server

build.gradle, docker-compose.yml, src/main/resources/application-dev.yml
이번에 수소에 배포하면서 모니터링 도구가 있으면 좋을 것 같아 Prometheus와 Grafana를 설치 및 설정 완료 했습니다. 이제 [https://h.princip.es/get-p/monitor](https://h.princip.es/get-p/monitor)에 접속하면 현재 애플리케이션에 대한 모니터링이 가능합니다. 자세한 사용 방법은 나중에 미팅때 알려드릴게요!
없음
없음
=> chore: Prometheus와 Grafana 설치 및 설정

src/main/java/es/princip/getp/domain/auth/repository/EmailVerificationRepository.java, src/main/java/es/princip/getp/domain/auth/repository/TokenVerificationRepository.java, src/main/java/es/princip/getp/global/config/RedisConfig.java, src/main/resources/junit-platform.properties
- 테스트 속도 개선을 위해 JUnit이 클래스 단위로 병렬 실행되도록 설정 했습니다. 제 로컬 환경 기준 빌드 시간이 35초에서 23초로 단축 되었습니다.
- 현재 Spring이 실행되면서 Spring Data Redis가 repository를 스캔하면서 Redis repository와 JPA repository를 안전하게 식별하지 못하는 문제가 있습니다. 에러가 발생하진 않지만, 매번 실행 시 경고문이 출력되기 때문에 수정을 하는 것이 좋아 보입니다.
-
=> chore: 테스트 속도 개선을 위해 JUnit 병렬 실행 단위를 클래스로 설정

src/main/java/es/princip/getp/domain/client/domain/entity/Client.java, src/main/java/es/princip/getp/domain/people/domain/entity/People.java, src/main/java/es/princip/getp/domain/project/controller/ProjectLikeController.java, src/main/java/es/princip/getp/domain/project/domain/entity/ProjectLike.java, src/main/java/es/princip/getp/domain/project/exception/ProjectLikeErrorCode.java, src/main/java/es/princip/getp/domain/project/repository/ProjectLikeRepository.java, src/main/java/es/princip/getp/domain/project/service/ProjectLikeService.java, src/test/java/es/princip/getp/domain/project/controller/ProjectLikeControllerTest.java, src/test/java/es/princip/getp/domain/project/repository/ProjectLikeRepositoryTest.java, src/test/java/es/princip/getp/domain/project/service/ProjectLikeServiceTest.java
- 피플이 관심있는 프로젝트에 좋아요를 누를 수 있는 기능을 구현했습니다.
- 좋아요를 누른 프로젝트 목록을 보는 API의 엔드 포인트가 고민입니다. 원래는 `Member` 엔티티에 `mappedBy`를 하려고 했는데 `People` 엔티티에 `mappedBy`를 걸게 돼서 살짝 고민이네요. 현재 생각했을 때 가장 좋은건 `GET /projects?liked=true`인 것 같아요. 다른 의견 있으시면 알려주세요!
-
=> GETP-114 feat: 프로젝트 좋아요 기능 구현

src/main/java/es/princip/getp/domain/auth/domain/entity/EmailVerification.java, src/main/java/es/princip/getp/domain/auth/domain/entity/TokenVerification.java, src/main/java/es/princip/getp/domain/auth/service/AuthService.java, src/main/java/es/princip/getp/domain/auth/service/EmailVerificationService.java, src/main/java/es/princip/getp/global/security/provider/JwtTokenProvider.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/test/java/es/princip/getp/domain/auth/service/EmailVerificationServiceTest.java, src/test/java/es/princip/getp/fixture/EmailVerificationFixture.java, src/test/resources/application-test.yml
- 개발 환경 및 스테이징 환경에서 테스트를 손쉽게 하기 위해 이메일 인증, Access Token, Refresh Token의 만료 시간을 configuration 가능하게 변경
- 
-
=> feat: 이메일 인증, Access Token, Refresh Token의 만료 시간을 configuration 가능하게 변경

.gitignore, src/docs/asciidoc/index.adoc, src/docs/asciidoc/member.adoc, src/main/java/es/princip/getp/domain/auth/service/SignUpService.java, src/main/java/es/princip/getp/domain/base/BaseTimeEntity.java, src/main/java/es/princip/getp/domain/client/dto/response/ClientResponse.java, src/main/java/es/princip/getp/domain/member/controller/MemberController.java, src/main/java/es/princip/getp/domain/member/domain/entity/Member.java, src/main/java/es/princip/getp/domain/member/domain/enums/MemberType.java, src/main/java/es/princip/getp/domain/member/dto/response/MemberResponse.java, src/main/java/es/princip/getp/domain/people/dto/response/people/CreatePeopleResponse.java, src/main/java/es/princip/getp/domain/people/dto/response/people/PeopleResponse.java, src/main/java/es/princip/getp/domain/people/dto/response/people/UpdatePeopleResponse.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/test/java/es/princip/getp/domain/member/controller/MemberControllerTest.java, src/test/java/es/princip/getp/global/mock/WithCustomMockUser.java, src/test/java/es/princip/getp/global/mock/WithCustomMockUserSecurityContextFactory.java, src/test/java/es/princip/getp/global/support/AbstractControllerTest.java, src/test/resources/application-test.yml
- 내 사용자 정보 조회 기능 구현
- 현재 닉네임 필드가 Client 테이블 또는 People 테이블에 있는데, 피플 정보 또는 의뢰자 정보를 기입하지 않은 경우 닉네임의 기본값으로 어떤 값을 반환해줄지 고민입니다. 일단은 이메일 주소를 `@`를 기준으로 파싱해서 반환하는 것으로 처리했습니다.
-
=> feat: 내 사용자 정보 조회 기능 구현

src/main/java/es/princip/getp/domain/client/domain/entity/Client.java, src/main/java/es/princip/getp/domain/member/controller/MemberController.java, src/main/java/es/princip/getp/domain/member/domain/entity/Member.java, src/main/java/es/princip/getp/domain/member/dto/response/MemberResponse.java, src/main/java/es/princip/getp/domain/people/domain/entity/People.java, src/test/java/es/princip/getp/domain/member/controller/MemberControllerTest.java
- 내 회원 정보 조회 시 피플 또는 의뢰자 정보를 등록하지 않은 경우 404를 반환하는 오류 수정
-
-
=> fix: 내 회원 정보 조회 시 피플 또는 의뢰자 정보를 등록하지 않은 경우 404를 반환하는 오류 수정

src/docs/asciidoc/index.adoc, src/docs/asciidoc/people/get-card-people-page.adoc, src/main/java/es/princip/getp/domain/people/controller/PeopleController.java, src/main/java/es/princip/getp/domain/people/domain/enums/PeopleOrder.java, src/main/java/es/princip/getp/domain/people/repository/PeopleQueryDslRepositoryImpl.java, src/main/java/es/princip/getp/global/domain/dto/response/PageResponse.java, src/main/java/es/princip/getp/global/util/StringUtil.java, src/test/java/es/princip/getp/domain/people/controller/PeopleControllerTest.java, src/test/java/es/princip/getp/domain/people/fixture/PeopleFixture.java, src/test/java/es/princip/getp/domain/people/fixture/PeopleProfileFixture.java, src/test/java/es/princip/getp/global/support/PageResponseDescriptor.java, src/test/resources/org/springframework/restdocs/templates/asciidoctor/query-parameters.snippet
- 피플 목록 조회 컨트롤러 단위 테스트 및 API 문서 작성
- 스프링의 기본 Page 객체에서 필요 없는 필드를 반환하지 않도록 페이지 객체 DTO `PageResponse` 구현
- `?sort=peopleId,desc`, `?sort=PEOPLE_ID,desc`, `?sort=people_id,desc`와 같이 API 사용 시 정렬 기준을 유연하게 작성할 수 있도록 구현
- 
-
=> GETP-143 test: 피플 목록 조회 컨트롤러 단위 테스트 및 API 문서 작성

src/docs/asciidoc/auth/reissue-access-token.adoc, src/docs/asciidoc/index.adoc, src/main/java/es/princip/getp/domain/auth/controller/AuthController.java, src/test/java/es/princip/getp/domain/auth/controller/AuthControllerTest.java
-  Access Token과 Refresh Token 재발급 컨트롤러 단위 테스트 및 API 문서 작성
- 
-
=> GETP-142 test: Access Token과 Refresh Token 재발급 컨트롤러 단위 테스트 및 API 문서 작성

src/docs/asciidoc/index.adoc, src/docs/asciidoc/people/get-my-people.adoc, src/main/java/es/princip/getp/domain/people/domain/entity/People.java, src/test/java/es/princip/getp/domain/people/controller/MyPeopleControllerTest.java, src/test/java/es/princip/getp/domain/people/fixture/PeopleFixture.java, src/test/java/es/princip/getp/domain/people/service/PeopleServiceTest.java
- 내 피플 정보 조회 컨트롤러 단위 테스트 및 API 문서 작성
- 수소 서버 CI/CD 재설정
- 임시 서버에서 수소 서버로 DNS 재설정
- 수소 서버에 `*.princip.es`로 Cloudflare TLS 인증서 설정
- 
-
=> GETP-144 test: 내 피플 정보 조회 컨트롤러 단위 테스트 및 API 문서 작성

build.gradle, src/main/java/es/princip/getp/domain/common/domain/URL.java, src/main/java/es/princip/getp/domain/common/infra/URLMapper.java, src/main/java/es/princip/getp/domain/people/command/domain/PeopleProfileChecker.java, src/main/java/es/princip/getp/domain/people/exception/PeopleProfileNotRegisteredException.java, src/main/java/es/princip/getp/domain/project/command/application/ProjectApplicationService.java, src/main/java/es/princip/getp/domain/project/command/application/ProjectService.java, src/main/java/es/princip/getp/domain/project/command/application/command/ApplyProjectCommand.java, src/main/java/es/princip/getp/domain/project/command/domain/AttachmentFile.java, src/main/java/es/princip/getp/domain/project/command/domain/ExpectedDuration.java, src/main/java/es/princip/getp/domain/project/command/domain/ProjectApplier.java, src/main/java/es/princip/getp/domain/project/command/infra/ProjectMapper.java, src/main/java/es/princip/getp/domain/project/command/presentation/ProjectApplicationController.java, src/main/java/es/princip/getp/domain/project/command/presentation/dto/request/ApplyProjectRequest.java, src/main/java/es/princip/getp/domain/project/command/presentation/dto/request/RegisterProjectRequest.java, src/test/java/es/princip/getp/domain/common/infra/URLMapperTest.java, src/test/java/es/princip/getp/domain/project/command/infra/ProjectMapperTest.java, src/test/java/es/princip/getp/domain/project/command/presentation/ProjectApplicationControllerTest.java
- 프로젝트 지원에 대한 비즈니스 로직을 `PeopleApplicationService`에서 분리
- DTO 개수가 늘어남에 따라 효율적으로 관리하기 위해 `MapStruct` 의존성 설치
- 
-
=> refactor: 프로젝트 지원에 대한 비즈니스 로직을 PeopleApplicationService에서 분리

src/main/java/es/princip/getp/domain/member/query/dto/MemberResponse.java
- 내 회원 정보 조회에서 닉네임, 프로필 이미지를 등록하지 않은 경우 NPE가 발생하는 오류 수정
- 
-
=> fix: 내 회원 정보 조회에서 닉네임, 프로필 이미지를 등록하지 않은 경우 NPE가 발생하는 오류 수정

src/docs/asciidoc/index.adoc, src/docs/asciidoc/my-client/register-my-client.adoc, src/main/java/es/princip/getp/domain/client/command/application/ClientService.java, src/main/java/es/princip/getp/domain/client/command/application/command/RegisterClientCommand.java, src/main/java/es/princip/getp/domain/client/command/presentation/MyClientController.java, src/main/java/es/princip/getp/domain/client/command/presentation/dto/request/RegisterMyClientRequest.java, src/main/java/es/princip/getp/domain/member/command/application/command/UpdateMemberCommand.java, src/test/java/es/princip/getp/domain/client/command/application/ClientServiceTest.java, src/test/java/es/princip/getp/domain/client/command/presentation/MyClientControllerTest.java, src/test/java/es/princip/getp/domain/client/command/presentation/description/RegisterMyClientRequestDescription.java
- 의뢰자 정보 등록 컨트롤러 단위 테스트 작성
- 도메인 모델에서 다음 행위에 대한 명칭을 이와 같이 통일하려고 합니다. 단순히 Create, Update라고 명칭하는 것 보다는 더 비즈니스 적인 의미가 담기도록 하는 것이 좋을 것 같습니다.
- 등록하다: Register
- 수정하다: Edit
-
=> GETP-161 test: 의뢰자 정보 등록 컨트롤러 단위 테스트 작성

src/main/java/es/princip/getp/domain/auth/infra/EmailVerificationCodeSender.java, src/main/java/es/princip/getp/domain/common/annotation/DomainService.java, src/main/java/es/princip/getp/domain/people/command/domain/PeopleProfileChecker.java, src/main/java/es/princip/getp/domain/project/command/domain/ProjectApplier.java, src/main/java/es/princip/getp/domain/project/command/domain/ProjectCommissioner.java, src/main/java/es/princip/getp/domain/project/command/domain/ProjectMeetingScheduler.java, src/main/java/es/princip/getp/domain/project/command/infra/EmailMeetingSender.java, src/main/java/es/princip/getp/infra/mail/EmailSender.java
- `MailSender` Bean 중복 등록과 `@DomainService`로 인한 스프링 컨텍스트 로드 실패 오류 수정
- 이와 같은 일을 방지하고자 컨텍스트 로드에 대한 테스트를 만들어야 할 것 같습니다.
-
=> fix: `MailSender` Bean 중복 등록과 `@DomainService`로 인한 스프링 컨텍스트 로드 실패 오류 수정

docker-compose.yml, src/main/java/es/princip/getp/infra/storage/infra/LocalImageStorage.java, src/main/resources/application-dev.yml
- 사진 삭제 시 URI로부터 잘못된 경로를 생성하는 오류 수정
- 현재 사진 스토리지와 파일 스토리지가 유사한 로직을 가지고 있습니다. 이에 관해 리팩토링이 필요할 것 같습니다.
-
=> fix: 사진 삭제 시 URI로부터 잘못된 경로를 생성하는 오류 수정

src/main/java/es/princip/getp/domain/like/query/dao/PeopleLikeQueryDslDao.java, src/main/java/es/princip/getp/domain/like/query/dao/ProjectLikeQueryDslDao.java, src/main/java/es/princip/getp/domain/people/command/domain/People.java, src/main/java/es/princip/getp/domain/people/command/domain/PeopleProfile.java, src/main/java/es/princip/getp/domain/people/exception/NotRegisteredPeopleProfileException.java, src/test/java/es/princip/getp/domain/like/query/dao/ZeroTestSizePeopleLikeDaoTest.java
- 피플 프로필이 미등록 상태임에도 등록할 수 없는 오류 수정
- JPA의 `@Embeddable`에서, JPA의 구현체로 Hibernate를 사용하는 경우 `@Embeddable` 객체의 모든 필드가 `null`인 경우 Hibernate는 해당 객체 자체를 `null`로 설정합니다. 이를 이용해 `@Embeddable`인 `PeopleProfile`이 `null`인 경우 프로필을 등록하지 않은 것으로 판단했습니다. 그러나 `PeopleProfile` 객체의 `hastags`, `techStacks`, `portfolios`의 기본값이 `null`이 아니라 빈 `ArrayList`이기 때문에 모든 필드가 `null`이 아님으로 프로필을 등록하지 않아도 `PeopleProfile`이 `null`이 아니게 되어 버그가 발생했었습니다. 이를 이번 PR과 같이 수정하였습니다.
-
=> GETP-185 fix: 피플 프로필이 미등록 상태임에도 등록할 수 없는 오류 수정

src/main/java/es/princip/getp/persistence/adapter/member/MemberJpaEntity.java
- `MemberJpaEntity`의 builder에서 초기화 표현식을 무시하지 않도록 `@Builder.Default` 추가
- 
-
=> GETP-196 fix: `MemberJpaEntity`의 builder에서 초기화 표현식을 무시하지 않도록 `@Builder.Default` 추가

src/main/java/es/princip/getp/domain/like/people/model/PeopleLike.java, src/main/java/es/princip/getp/domain/like/project/model/ProjectLike.java, src/main/java/es/princip/getp/persistence/adapter/like/people/PeopleLikeJpaEntity.java, src/main/java/es/princip/getp/persistence/adapter/like/project/ProjectLikeJpaEntity.java
- people_like 테이블과 project_like 테이블의 primary key 이름을 JPA 매핑에 맞게 변경
- 
-
=> GETP-224 fix: people_like 테이블과 project_like 테이블의 primary key 이름을 JPA 매핑에 맞게 변경

src/main/java/es/princip/getp/api/controller/client/command/dto/request/EditMyClientRequest.java, src/main/java/es/princip/getp/api/controller/client/command/dto/request/RegisterMyClientRequest.java, src/main/java/es/princip/getp/api/controller/client/query/dto/ClientResponse.java, src/main/java/es/princip/getp/application/client/command/EditClientCommand.java, src/main/java/es/princip/getp/application/client/command/RegisterClientCommand.java, src/main/java/es/princip/getp/application/client/service/EditClientService.java, src/main/java/es/princip/getp/application/client/service/RegisterClientService.java, src/main/java/es/princip/getp/domain/client/model/Client.java, src/main/java/es/princip/getp/domain/common/model/BankAccount.java, src/main/java/es/princip/getp/persistence/adapter/client/ClientPersistenceMapper.java, src/main/java/es/princip/getp/persistence/adapter/client/ClientQueryDslQuery.java, src/test/java/es/princip/getp/api/controller/client/command/MyClientControllerTest.java, src/test/java/es/princip/getp/api/controller/client/command/description/BankAccountDescription.java, src/test/java/es/princip/getp/api/controller/client/command/description/EditMyClientRequestDescription.java, src/test/java/es/princip/getp/api/controller/client/command/description/RegisterMyClientRequestDescription.java, src/test/java/es/princip/getp/api/controller/client/query/ClientQueryControllerTest.java, src/test/java/es/princip/getp/api/controller/client/query/MyClientQueryControllerTest.java, src/test/java/es/princip/getp/api/controller/client/query/description/ClientResponseDescription.java, src/test/java/es/princip/getp/api/controller/common/description/BankAccountDescription.java, src/test/java/es/princip/getp/domain/client/model/BankAccountTest.java, src/test/java/es/princip/getp/domain/common/model/BankAccountTest.java, src/test/java/es/princip/getp/fixture/client/BankAccountFixture.java, src/test/java/es/princip/getp/fixture/client/ClientFixture.java
- 의뢰자 정보 도메인 모델에서 계좌 필드 삭제
- X
- `BankAccountVO`는 나중에 관리 도메인에서 사용 예정이기 때문에, 삭제하지 않고 공통 모델로 이동하였습니다.
=> GETP-275 feat: 의뢰자 정보 도메인 모델에서 계좌 필드 삭제

src/main/java/es/princip/getp/application/people/command/PeopleSearchFilter.java, src/main/java/es/princip/getp/persistence/adapter/people/FindPeopleAdapter.java, src/test/java/es/princip/getp/api/controller/people/query/description/GetCardPeoplePageQueryParametersDescription.java, src/test/java/es/princip/getp/persistence/adapter/member/MemberDataLoader.java, src/test/java/es/princip/getp/persistence/adapter/people/FindPeopleAdapterTest.java
- 피플 닉네임으로 검색 기능 구현
- 현재 피플을 검색하는 기능이 피플 목록 조회 페이지와 프로젝트 지원 페이지에서 필요로 하고 있어요. 피플 목록 조회에서는 닉네임이 사용자가 검색한 키워드로 시작하는 피플을 검색하는 기능이 필요하고, 프로젝트 지원에서는 아직 정해지지 않았지만 팀원 검색을 위해 비슷한 기능을 필요로 해요. 다만, 프로젝트 지원에서 사용자가 검색한 키워드로 시작하는 피플을 모두 검색을 할지, 아니면 사용자가 검색한 키워드와 일치하는 피플만 검색을 할지 결정에 따라 API 구현 방법이 달라질 것 같아요. 또한 무한 스크롤 지원 여부에 대한 결정도 필요해요.
-
=> GETP-270 feat: 피플 닉네임으로 검색 기능 구현

src/main/java/es/princip/getp/domain/project/commission/model/ProjectCategory.java, src/main/resources/db/migration/V6__add_project_category_etc.sql, src/test/java/es/princip/getp/api/controller/project/command/description/CommissionProjectRequestDescription.java, src/test/java/es/princip/getp/api/controller/project/query/description/ProjectDetailResponseDescription.java
- 프로젝트 카테고리에 기타 필드 추가
- 현재 API 문서에서 필드 타입이 열거형인 경우, 설명이 부족한 상태에요. 이를 쉽고 편하게 해결하는 방법에 대한 고민이 필요해요.
-
=> GETP-292 feat: 프로젝트 카테고리에 기타 필드 추가

src/main/java/es/princip/getp/api/handler/MaxUploadSizeExceededExceptionHandler.java, src/main/java/es/princip/getp/application/storage/FileLog.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml
=> GETP-310 feat: 파일 업로드 최대 용량 5MB로 변경
